import UIKit
import OSLog

/// Disk + memory cache for generated food photography.
///
/// Keyed by the *normalised food name*, not by entry id. That one decision does three
/// things at once: the same food looks identical everywhere it appears in the catalog,
/// a food is only ever paid for once, and logging something you eat often is instant
/// from the second time onward.
final class ImageCache: @unchecked Sendable {
    static let shared = ImageCache()

    // NSCache is documented as thread-safe, and UIImage is immutable once created —
    // which is what makes the unchecked conformance above honest rather than a hope.
    private let memory = NSCache<NSString, UIImage>()
    private let directory: URL
    private let logger = Logger(subsystem: "com.plate.Plate", category: "ImageCache")

    init(directory: URL? = nil) {
        let location = directory ?? URL.cachesDirectory.appending(path: "Plate/food-images")
        self.directory = location
        try? FileManager.default.createDirectory(at: location, withIntermediateDirectories: true)
        memory.countLimit = 120
        // Roughly 40 MB of decoded images; the catalog can have a lot on screen at once.
        memory.totalCostLimit = 40 * 1024 * 1024
    }

    /// Where an image comes from. Both are cached the same way; they differ only in
    /// that a procedural render is superseded when the renderer changes.
    enum Kind: Hashable, Sendable {
        case photographed
        case rendered
    }

    /// The stable file name for a food. Safe for the file system and stable across
    /// launches, unlike anything derived from `hashValue`.
    static func key(forFood name: String, kind: Kind = .photographed) -> String {
        let normalized = NutritionDatabase.normalize(name).replacingOccurrences(of: " ", with: "-")
        let trimmed = normalized.isEmpty ? "food" : String(normalized.prefix(60))
        // Suffix with a stable hash so two foods that normalise identically but read
        // differently still get their own file.
        let stem = "\(trimmed)-\(FoodEntry.seed(for: name))"
        switch kind {
        case .photographed: return "\(stem).jpg"
        case .rendered: return "\(stem)-r\(FoodSceneRenderer.version).jpg"
        }
    }

    func image(for fileName: String) -> UIImage? {
        if let cached = memory.object(forKey: fileName as NSString) { return cached }
        guard let data = try? Data(contentsOf: directory.appending(path: fileName)),
              let image = UIImage(data: data)
        else { return nil }
        store(image, data: data, for: fileName)
        return image
    }

    func hasImage(for fileName: String) -> Bool {
        memory.object(forKey: fileName as NSString) != nil
            || FileManager.default.fileExists(
                atPath: directory.appending(path: fileName).path(percentEncoded: false)
            )
    }

    /// Writes generated bytes to disk, re-encoding to JPEG so a PNG response doesn't
    /// cost 4× the space for a photograph.
    @discardableResult
    func write(_ data: Data, for fileName: String) -> UIImage? {
        guard let image = UIImage(data: data) else { return nil }
        let encoded = image.jpegData(compressionQuality: 0.86) ?? data
        do {
            try encoded.write(to: directory.appending(path: fileName), options: [.atomic])
        } catch {
            logger.error("Could not cache \(fileName): \(error.localizedDescription)")
        }
        store(image, data: encoded, for: fileName)
        return image
    }

    func removeAll() {
        memory.removeAllObjects()
        try? FileManager.default.removeItem(at: directory)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    }

    /// Bytes currently on disk, for the Settings screen.
    func diskUsage() -> Int64 {
        let contents = (try? FileManager.default.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: [.fileSizeKey]
        )) ?? []
        return contents.reduce(into: Int64(0)) { total, url in
            let size = try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize
            total += Int64(size ?? 0)
        }
    }

    private func store(_ image: UIImage, data: Data, for fileName: String) {
        memory.setObject(image, forKey: fileName as NSString, cost: data.count)
    }
}
